version: "3.8"

services:
  configserver:
    build:
      context: ../configserver
      dockerfile: ../docker_dev/Dockerfile.configserver.dev
    container_name: configserver-dev
    ports:
      - "8071:8071"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    env_file:
      - configserver.env
    networks:
      - microservice-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.1"
          memory: "256M"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  eureka-server:
    build:
      context: ../eureka-server
      dockerfile: ../docker_dev/Dockerfile.eureka.dev
    container_name: eureka-server-dev
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - microservice-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.1"
          memory: "256M"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  account:
    build:
      context: ../account
      dockerfile: ../docker_dev/Dockerfile.account.dev
    container_name: account-dev
    ports:
      - "8080:8080"
    env_file:
      - account.env
    depends_on:
      configserver:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071
      - EUREKA_HOST=http://eureka-server:8761/eureka/
    networks:
      - microservice-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.1"
          memory: "256M"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  microservice-net:
    driver: bridge
