version: "3.8"

services:
  configserver:
    build:
      context: ../configserver
      dockerfile: ../docker_dev/Dockerfile.configserver.dev
    container_name: configserver-dev
    ports:
      - "8071:8071"
    environment:
      - SPRING_PROFILES_ACTIVE=git
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
    env_file:
      - .env
    networks:
      - microservice-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.1"
          memory: "256M"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  account:
    build:
      context: ../account
      dockerfile: ../docker_dev/Dockerfile.account.dev
    container_name: account-dev
    ports:
      - "8081:8081"
    depends_on:
      - configserver
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8071
    networks:
      - microservice-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.1"
          memory: "256M"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  microservice-net:
    driver: bridge
